redirect errors to fd2, not to file called 2 in bg
replace >2& with >&2

diff --git a/swaymaxxing b/swaymaxxing
--- a/swaymaxxing
+++ b/swaymaxxing
@@ -16,7 +16,7 @@ for pkg in "${required[@]}"
 do
     if ! command -v "$pkg" > /dev/null 2>&1
     then
-        echo "Error: missing '$pkg'" >2&
+        echo "Error: missing '$pkg'" >&2
         exit 1
     fi
 done
@@ -26,7 +26,7 @@ done
 # a subshell)
 if (( BASH_VERSINFO[0] < 5 || BASH_VERSINFO[1] < 3 ))
 then
-    echo "Error: Bash version is older than 5.3" >2&
+    echo "Error: Bash version is older than 5.3" >&2
     exit 1
 fi
 
